services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo_container
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mynetwork
    logging:
      driver: "none"

  fast_api:
    container_name: aflot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    #volumes:
    #  - ./api:/api
    #  - ./models:/models
    #  - ./schemas:/schemas
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /api
        - action: sync+restart
          path: ./models
          target: /models
        - action: sync+restart
          path: ./schemas
          target: /schemas
    networks:
      - mynetwork
    depends_on:
      - mongo

  starlette_admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./Dockerfile_admin
    ports:
      - "8001:8001"
    develop:
      watch:
        - action: sync+restart
          path: ./translations
          target: /translations
        - action: sync+restart
          path: ./venv/Lib/site-packages/starlette_admin
          target: /venv/Lib/site-packages/starlette_admin
        - action: sync+restart
          path: ./af_admin
          target: /af_admin
        - action: sync+restart
          path: ./admin_app.py
          target: /admin_app.py
    networks:
      - mynetwork
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge